Platzigram/Platzigram/urls.py
# django
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

# local_views
from . import views as local_views



urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),

    path('', include(('users.urls', 'users'), namespace='profile')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Platzigram/posts/urls.py
"""Posts URLs"""

# django
from django.urls import path

# views
from posts import views

urlpatterns = [

    path(
        route = '', 
        view = views.ListPostView.as_view(),
        name = 'feed'),
    
    path(
        route = 'new',
        view = views.CreatePostView.as_view(),
        name="create"),

    path(
        route = 'posts/<int:pk>/',
        view = views.PostDetailView.as_view(),
        name='detail'
    )
]

Platzigram/users/urls.py
"""Users URLs"""

# django
from django.urls import path

# views
from users import views


urlpatterns = [

    # Managment
    path(
        route = 'profile/login/',
        view = views.LoginView.as_view(),
        name='login'
    ),
    
    path(
        route = 'profile/logout/',
        view = views.LogoutView.as_view(),
        name='logout'
    ),

    path(
        route = 'profile/signup/',
        view = views.SignupView.as_view(),
        name='signup'
    ),

    path(
        route = 'profile/me/update_profile',
        view = views.UpdateProfileView.as_view(),
        name='update'
    ),

    # Posts
    path(
        route = 'profile/<str:username>/',
        view = views.UserDetailView.as_view(),
        name = 'detail'
    ),


]

Platzigram/users/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    # Profile Model
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(
        max_length=200,
        blank=True
    )
    
    biography = models.TextField(blank=True)
    
    phone_number = models.CharField(max_length=20, blank=True)
    
    picture = models.ImageField(
        upload_to="users/picture",
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """return username"""
        return self.user.username

Platzigram/users/forms.py
""" Users forms"""

# django
from django import forms

# models
from users.models import Profile
from django.contrib.auth.models import User

class UpdateForm(forms.Form):
    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=200, required=True)
    phone_number = forms.CharField(max_length=20, required=True)
    picture = forms.ImageField()

class SignupForm(forms.Form):

    username = forms.CharField(min_length=4, max_length=50)
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(),
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput(),
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(),
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username is already in use')
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already in use')
        return email

    def clean(self):
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Password doesnt match')
            
        return data
    
    def save(self):
        """Create user and profile"""
        data = self.cleaned_data
        data.pop('password_confirmation')


        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()
            

Platzigram/users/views.py
"""User App Views"""

# django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# views
from django.views.generic import FormView, UpdateView, DetailView
from django.contrib.auth.views import LoginView, LogoutView

# models
from users.models import Profile
from posts.models import Post
from django.contrib.auth.models import User

# forms
from users.forms import UpdateForm, SignupForm


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""
    
    template_name = "users/detail.html"
    slug_field = 'username'                 # campo slug de la bd
    slug_url_kwarg = 'username'             # campo slug enviado por la url <str:'username'>
    queryset = User.objects.all()
    contex_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')

        return context

class SignupView(FormView):
    """Users Signup View"""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update Profile View"""

    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'phone_number', 'biography', 'picture']

    def get_object(self):
        """Return user's profile"""
        return self.request.user.profile
    
    def get_success_url(self):
        """Reteurns to user's profile"""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username':username})
    
class LogoutView(LoginRequiredMixin, LogoutView):
    """Logout view."""

    template_name = 'users/login.html'


class LoginView(LoginView):
    """Login view."""

    template_name = 'users/login.html'

def login_view(request):
    """User login view"""
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('posts:feed')
        else:
            error = "Invalid User or Password."
            return render(request, "users/login.html", {'error':error})

    return render(request, "users/login.html")

@login_required
def logout_view(request):
    """Logout user view"""
    logout(request)
    return redirect('users:login')

Platzigram/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock %}

            </div>
        </div>
    </div>

</body>
</html>

Platzigram/templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block content %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="150px"
                />
            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}785</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url "posts:detail" post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

Platzigram/templates/users/login.html
{% extends 'users/base.html' %}

{% block head %}
<title> Login </title>
{% endblock %}

{% block container %}

    {% if form.errors %}

        <p class="alert alert-danger">Please enter a correct username and password. Note that both fields may be case-sensitive.</p>
    {% endif %}

    {% if alert %}
        <p class="alert alert-success">{{ alert }}</p>
    {% endif %}

    <form action="{% url 'users:login'%}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" placeholder = "Username" name="username" class="form-control">
        </div>

        <div class="form-group">
            <input type="password" placeholder = "Password" name="password" class="form-control">
        </div>

        <button class="btn btn-primary btn-block mt-5" type="submit">Login!</button>

    </form> 

    <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}"> Sign up here!. </a></a></p>

{% endblock%}

Platzigram/templates/users/signup.html
{% extends 'users/base.html'%}

{% block head %}
<title> Sign Up!</title>
{% endblock %}

{% block container %}
    {% if error %}
    <p class="alert alert-danger">{{ error }}</p>
    {% endif %}
    
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Sign Up!</button>   

    </form>  
{% endblock %}

Platzigram/templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}
 
{% block head %}
<title>@{{ request.user.username }} | Update profiles</title>
{% endblock %}
 
{% block content %}
 
<div class="container">
 
    <div class="row justify-content-md-center">
        <div class="col-6 p-4"id="profile-box">
 
            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                 <div class='media'>
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}"class="rounded-circle"height="50"/>
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}"class="rounded-circle"height="50"/>
                    {% endif %}
                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{user.get_full_name}}</h5>
                        <p class="ml-4"><input type="file" name="picture" requerid="true"></p>
                    </div>
                </div>

                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                    {% endfor %}
                {% endif %}
          
 
                <hr><br>
 
                <div class="form-group">
                    <label>Website</label>
                    <input 
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}" 
                        type="url" name="website" 
                        placeholder="Website" 
                        value="{% if form.website.errors %} {{ form.website.value }} {% else %} {{ profile.website }} {% endif %}"
                    >
                    <div class="invalid-feedback">
                        {{ form.website.errors }}
                    </div>
                </div>
 
                <div class="form-group">
                    <label>Biography</label>
                    <textarea 
                        class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                        name="biography"
                    >{% if form.biography.errors %} {{ form.biography.value }} {% else %} {{ profile.biography }} {% endif %}
                    </textarea>
                    <div class="invalid-feedback">
                        {{ form.biography.errors }}
                    </div>
                </div>
 
                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.phone_number.errors %} {{ form.phone_number.value }} {% else %} {{ profile.phone_number }} {% endif %}"
                    />
                    <div class="invalid-feedback">
                        {{ form.phone_number.errors }}
                    </div>
                </div>
 
                <button type="submit"class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}