Platzigram/Platzigram/urls.py
# django
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include

# local_views
from . import views as local_views



urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),

    path('', include(('users.urls', 'users'), namespace='profile')),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Platzigram/posts/urls.py
"""Posts URLs"""

# django
from django.urls import path

# views
from posts import views

urlpatterns = [

    path(
        route = '', 
        view = views.ListPostView.as_view(),
        name = 'feed'),
    
    path(
        route = 'new',
        view = views.CreatePostView.as_view(),
        name="create"),

    path(
        route = 'posts/<int:pk>/',
        view = views.PostDetailView.as_view(),
        name='detail'
    )
]

Platzigram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %} {% endblock %}
    
    {% load static %}
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/main.css" %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    

</head>

<body>
    {% include "nav.html" %}
    
    <div class="container mt-5">
        {% block content %}
        {% endblock%}
    </div>
</body>
</html>

Platzigram/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else%}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "posts:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

Platzigram/templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>